/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.ui.tests;

import casinoMdd.ui.internal.CasinoMddActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CasinoMddActivator.getInstance().getInjector("org.xtext.example.mydsl.MyDsl");
	}

}
