/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.AbstractClass;
import org.xtext.example.mydsl.myDsl.AbstractMethod;
import org.xtext.example.mydsl.myDsl.Annotation;
import org.xtext.example.mydsl.myDsl.Attribute;
import org.xtext.example.mydsl.myDsl.MethodBack;
import org.xtext.example.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Abstract Class</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.AbstractClassImpl#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.AbstractClassImpl#getMethodClass <em>Method Class</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.AbstractClassImpl#getAnnotation <em>Annotation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.AbstractClassImpl#getAbstractMethod <em>Abstract Method</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AbstractClassImpl extends EclassImpl implements AbstractClass
{
  /**
   * The cached value of the '{@link #getAttribute() <em>Attribute</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAttribute()
   * @generated
   * @ordered
   */
  protected EList<Attribute> attribute;

  /**
   * The cached value of the '{@link #getMethodClass() <em>Method Class</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMethodClass()
   * @generated
   * @ordered
   */
  protected EList<MethodBack> methodClass;

  /**
   * The cached value of the '{@link #getAnnotation() <em>Annotation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAnnotation()
   * @generated
   * @ordered
   */
  protected Annotation annotation;

  /**
   * The cached value of the '{@link #getAbstractMethod() <em>Abstract Method</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAbstractMethod()
   * @generated
   * @ordered
   */
  protected EList<AbstractMethod> abstractMethod;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AbstractClassImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.ABSTRACT_CLASS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Attribute> getAttribute()
  {
    if (attribute == null)
    {
      attribute = new EObjectContainmentEList<Attribute>(Attribute.class, this, MyDslPackage.ABSTRACT_CLASS__ATTRIBUTE);
    }
    return attribute;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<MethodBack> getMethodClass()
  {
    if (methodClass == null)
    {
      methodClass = new EObjectContainmentEList<MethodBack>(MethodBack.class, this, MyDslPackage.ABSTRACT_CLASS__METHOD_CLASS);
    }
    return methodClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Annotation getAnnotation()
  {
    if (annotation != null && annotation.eIsProxy())
    {
      InternalEObject oldAnnotation = (InternalEObject)annotation;
      annotation = (Annotation)eResolveProxy(oldAnnotation);
      if (annotation != oldAnnotation)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.ABSTRACT_CLASS__ANNOTATION, oldAnnotation, annotation));
      }
    }
    return annotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Annotation basicGetAnnotation()
  {
    return annotation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAnnotation(Annotation newAnnotation)
  {
    Annotation oldAnnotation = annotation;
    annotation = newAnnotation;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.ABSTRACT_CLASS__ANNOTATION, oldAnnotation, annotation));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<AbstractMethod> getAbstractMethod()
  {
    if (abstractMethod == null)
    {
      abstractMethod = new EObjectContainmentEList<AbstractMethod>(AbstractMethod.class, this, MyDslPackage.ABSTRACT_CLASS__ABSTRACT_METHOD);
    }
    return abstractMethod;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.ABSTRACT_CLASS__ATTRIBUTE:
        return ((InternalEList<?>)getAttribute()).basicRemove(otherEnd, msgs);
      case MyDslPackage.ABSTRACT_CLASS__METHOD_CLASS:
        return ((InternalEList<?>)getMethodClass()).basicRemove(otherEnd, msgs);
      case MyDslPackage.ABSTRACT_CLASS__ABSTRACT_METHOD:
        return ((InternalEList<?>)getAbstractMethod()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.ABSTRACT_CLASS__ATTRIBUTE:
        return getAttribute();
      case MyDslPackage.ABSTRACT_CLASS__METHOD_CLASS:
        return getMethodClass();
      case MyDslPackage.ABSTRACT_CLASS__ANNOTATION:
        if (resolve) return getAnnotation();
        return basicGetAnnotation();
      case MyDslPackage.ABSTRACT_CLASS__ABSTRACT_METHOD:
        return getAbstractMethod();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.ABSTRACT_CLASS__ATTRIBUTE:
        getAttribute().clear();
        getAttribute().addAll((Collection<? extends Attribute>)newValue);
        return;
      case MyDslPackage.ABSTRACT_CLASS__METHOD_CLASS:
        getMethodClass().clear();
        getMethodClass().addAll((Collection<? extends MethodBack>)newValue);
        return;
      case MyDslPackage.ABSTRACT_CLASS__ANNOTATION:
        setAnnotation((Annotation)newValue);
        return;
      case MyDslPackage.ABSTRACT_CLASS__ABSTRACT_METHOD:
        getAbstractMethod().clear();
        getAbstractMethod().addAll((Collection<? extends AbstractMethod>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ABSTRACT_CLASS__ATTRIBUTE:
        getAttribute().clear();
        return;
      case MyDslPackage.ABSTRACT_CLASS__METHOD_CLASS:
        getMethodClass().clear();
        return;
      case MyDslPackage.ABSTRACT_CLASS__ANNOTATION:
        setAnnotation((Annotation)null);
        return;
      case MyDslPackage.ABSTRACT_CLASS__ABSTRACT_METHOD:
        getAbstractMethod().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.ABSTRACT_CLASS__ATTRIBUTE:
        return attribute != null && !attribute.isEmpty();
      case MyDslPackage.ABSTRACT_CLASS__METHOD_CLASS:
        return methodClass != null && !methodClass.isEmpty();
      case MyDslPackage.ABSTRACT_CLASS__ANNOTATION:
        return annotation != null;
      case MyDslPackage.ABSTRACT_CLASS__ABSTRACT_METHOD:
        return abstractMethod != null && !abstractMethod.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //AbstractClassImpl
