/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.example.mydsl.myDsl.Descriptor;
import org.xtext.example.mydsl.myDsl.Epackage;
import org.xtext.example.mydsl.myDsl.Library;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Subproject;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Subproject</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubprojectImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubprojectImpl#getEpackage <em>Epackage</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubprojectImpl#getLibrary <em>Library</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.SubprojectImpl#getDescriptor <em>Descriptor</em>}</li>
 * </ul>
 *
 * @generated
 */
public class SubprojectImpl extends MinimalEObjectImpl.Container implements Subproject
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getEpackage() <em>Epackage</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEpackage()
   * @generated
   * @ordered
   */
  protected EList<Epackage> epackage;

  /**
   * The cached value of the '{@link #getLibrary() <em>Library</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getLibrary()
   * @generated
   * @ordered
   */
  protected EList<Library> library;

  /**
   * The cached value of the '{@link #getDescriptor() <em>Descriptor</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDescriptor()
   * @generated
   * @ordered
   */
  protected EList<Descriptor> descriptor;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SubprojectImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.SUBPROJECT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.SUBPROJECT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Epackage> getEpackage()
  {
    if (epackage == null)
    {
      epackage = new EObjectContainmentEList<Epackage>(Epackage.class, this, MyDslPackage.SUBPROJECT__EPACKAGE);
    }
    return epackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Library> getLibrary()
  {
    if (library == null)
    {
      library = new EObjectContainmentEList<Library>(Library.class, this, MyDslPackage.SUBPROJECT__LIBRARY);
    }
    return library;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<Descriptor> getDescriptor()
  {
    if (descriptor == null)
    {
      descriptor = new EObjectContainmentEList<Descriptor>(Descriptor.class, this, MyDslPackage.SUBPROJECT__DESCRIPTOR);
    }
    return descriptor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBPROJECT__EPACKAGE:
        return ((InternalEList<?>)getEpackage()).basicRemove(otherEnd, msgs);
      case MyDslPackage.SUBPROJECT__LIBRARY:
        return ((InternalEList<?>)getLibrary()).basicRemove(otherEnd, msgs);
      case MyDslPackage.SUBPROJECT__DESCRIPTOR:
        return ((InternalEList<?>)getDescriptor()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBPROJECT__NAME:
        return getName();
      case MyDslPackage.SUBPROJECT__EPACKAGE:
        return getEpackage();
      case MyDslPackage.SUBPROJECT__LIBRARY:
        return getLibrary();
      case MyDslPackage.SUBPROJECT__DESCRIPTOR:
        return getDescriptor();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBPROJECT__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.SUBPROJECT__EPACKAGE:
        getEpackage().clear();
        getEpackage().addAll((Collection<? extends Epackage>)newValue);
        return;
      case MyDslPackage.SUBPROJECT__LIBRARY:
        getLibrary().clear();
        getLibrary().addAll((Collection<? extends Library>)newValue);
        return;
      case MyDslPackage.SUBPROJECT__DESCRIPTOR:
        getDescriptor().clear();
        getDescriptor().addAll((Collection<? extends Descriptor>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBPROJECT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.SUBPROJECT__EPACKAGE:
        getEpackage().clear();
        return;
      case MyDslPackage.SUBPROJECT__LIBRARY:
        getLibrary().clear();
        return;
      case MyDslPackage.SUBPROJECT__DESCRIPTOR:
        getDescriptor().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.SUBPROJECT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.SUBPROJECT__EPACKAGE:
        return epackage != null && !epackage.isEmpty();
      case MyDslPackage.SUBPROJECT__LIBRARY:
        return library != null && !library.isEmpty();
      case MyDslPackage.SUBPROJECT__DESCRIPTOR:
        return descriptor != null && !descriptor.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //SubprojectImpl
