/*
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.myDsl.AbstractClass;
import org.xtext.example.mydsl.myDsl.AbstractMethod;
import org.xtext.example.mydsl.myDsl.ActionCreator;
import org.xtext.example.mydsl.myDsl.ActionDispatcher;
import org.xtext.example.mydsl.myDsl.Annotation;
import org.xtext.example.mydsl.myDsl.Architecture;
import org.xtext.example.mydsl.myDsl.Attribute;
import org.xtext.example.mydsl.myDsl.AxiosRequest;
import org.xtext.example.mydsl.myDsl.Component;
import org.xtext.example.mydsl.myDsl.Container;
import org.xtext.example.mydsl.myDsl.Css;
import org.xtext.example.mydsl.myDsl.Descriptor;
import org.xtext.example.mydsl.myDsl.Directory;
import org.xtext.example.mydsl.myDsl.Domain;
import org.xtext.example.mydsl.myDsl.Einterface;
import org.xtext.example.mydsl.myDsl.EntityName;
import org.xtext.example.mydsl.myDsl.Epackage;
import org.xtext.example.mydsl.myDsl.Functionality;
import org.xtext.example.mydsl.myDsl.GeneralEntity;
import org.xtext.example.mydsl.myDsl.GenericClass;
import org.xtext.example.mydsl.myDsl.JavaApp;
import org.xtext.example.mydsl.myDsl.JeeProject;
import org.xtext.example.mydsl.myDsl.Js;
import org.xtext.example.mydsl.myDsl.JsMethod;
import org.xtext.example.mydsl.myDsl.JsMethodArgs;
import org.xtext.example.mydsl.myDsl.JsModule;
import org.xtext.example.mydsl.myDsl.Json;
import org.xtext.example.mydsl.myDsl.Layer;
import org.xtext.example.mydsl.myDsl.LayerSegment;
import org.xtext.example.mydsl.myDsl.LayerSegmentRelation;
import org.xtext.example.mydsl.myDsl.Library;
import org.xtext.example.mydsl.myDsl.Md;
import org.xtext.example.mydsl.myDsl.MethodBack;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.NativeClass;
import org.xtext.example.mydsl.myDsl.Operateson;
import org.xtext.example.mydsl.myDsl.Operation;
import org.xtext.example.mydsl.myDsl.Property;
import org.xtext.example.mydsl.myDsl.ReactApp;
import org.xtext.example.mydsl.myDsl.Reducer;
import org.xtext.example.mydsl.myDsl.RelationArch;
import org.xtext.example.mydsl.myDsl.RelationDom;
import org.xtext.example.mydsl.myDsl.RouterComponent;
import org.xtext.example.mydsl.myDsl.ServiceFront;
import org.xtext.example.mydsl.myDsl.SpecialEntity;
import org.xtext.example.mydsl.myDsl.State;
import org.xtext.example.mydsl.myDsl.SublayerSegment;
import org.xtext.example.mydsl.myDsl.Submodule;
import org.xtext.example.mydsl.myDsl.Subproject;
import org.xtext.example.mydsl.myDsl.Technology;
import org.xtext.example.mydsl.myDsl.Transaction;
import org.xtext.example.mydsl.myDsl.Type;
import org.xtext.example.mydsl.myDsl.Visualizer;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.ABSTRACT_CLASS:
				sequence_AbstractClass(context, (AbstractClass) semanticObject); 
				return; 
			case MyDslPackage.ABSTRACT_METHOD:
				sequence_AbstractMethod(context, (AbstractMethod) semanticObject); 
				return; 
			case MyDslPackage.ACTION:
				sequence_Action(context, (org.xtext.example.mydsl.myDsl.Action) semanticObject); 
				return; 
			case MyDslPackage.ACTION_CREATOR:
				sequence_ActionCreator(context, (ActionCreator) semanticObject); 
				return; 
			case MyDslPackage.ACTION_DISPATCHER:
				sequence_ActionDispatcher(context, (ActionDispatcher) semanticObject); 
				return; 
			case MyDslPackage.ANNOTATION:
				sequence_Annotation(context, (Annotation) semanticObject); 
				return; 
			case MyDslPackage.ARCHITECTURE:
				sequence_Architecture(context, (Architecture) semanticObject); 
				return; 
			case MyDslPackage.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case MyDslPackage.AXIOS_REQUEST:
				sequence_AxiosRequest(context, (AxiosRequest) semanticObject); 
				return; 
			case MyDslPackage.COMPONENT:
				sequence_Component(context, (Component) semanticObject); 
				return; 
			case MyDslPackage.CONTAINER:
				sequence_Container(context, (Container) semanticObject); 
				return; 
			case MyDslPackage.CSS:
				sequence_Css(context, (Css) semanticObject); 
				return; 
			case MyDslPackage.DESCRIPTOR:
				sequence_Descriptor(context, (Descriptor) semanticObject); 
				return; 
			case MyDslPackage.DIRECTORY:
				sequence_Directory(context, (Directory) semanticObject); 
				return; 
			case MyDslPackage.DOMAIN:
				sequence_Domain(context, (Domain) semanticObject); 
				return; 
			case MyDslPackage.EINTERFACE:
				sequence_Einterface(context, (Einterface) semanticObject); 
				return; 
			case MyDslPackage.ENTITY_NAME:
				sequence_EntityName(context, (EntityName) semanticObject); 
				return; 
			case MyDslPackage.EPACKAGE:
				sequence_Epackage(context, (Epackage) semanticObject); 
				return; 
			case MyDslPackage.FUNCTIONALITY:
				sequence_Functionality(context, (Functionality) semanticObject); 
				return; 
			case MyDslPackage.GENERAL_ENTITY:
				sequence_GeneralEntity(context, (GeneralEntity) semanticObject); 
				return; 
			case MyDslPackage.GENERIC_CLASS:
				sequence_GenericClass(context, (GenericClass) semanticObject); 
				return; 
			case MyDslPackage.JAVA_APP:
				sequence_JavaApp(context, (JavaApp) semanticObject); 
				return; 
			case MyDslPackage.JEE_PROJECT:
				sequence_JeeProject(context, (JeeProject) semanticObject); 
				return; 
			case MyDslPackage.JS:
				sequence_Js(context, (Js) semanticObject); 
				return; 
			case MyDslPackage.JS_METHOD:
				sequence_JsMethod(context, (JsMethod) semanticObject); 
				return; 
			case MyDslPackage.JS_METHOD_ARGS:
				sequence_JsMethodArgs(context, (JsMethodArgs) semanticObject); 
				return; 
			case MyDslPackage.JS_MODULE:
				sequence_JsModule(context, (JsModule) semanticObject); 
				return; 
			case MyDslPackage.JSON:
				sequence_Json(context, (Json) semanticObject); 
				return; 
			case MyDslPackage.LAYER:
				sequence_Layer(context, (Layer) semanticObject); 
				return; 
			case MyDslPackage.LAYER_SEGMENT:
				sequence_LayerSegment(context, (LayerSegment) semanticObject); 
				return; 
			case MyDslPackage.LAYER_SEGMENT_RELATION:
				sequence_LayerSegmentRelation(context, (LayerSegmentRelation) semanticObject); 
				return; 
			case MyDslPackage.LIBRARY:
				sequence_Library(context, (Library) semanticObject); 
				return; 
			case MyDslPackage.MD:
				sequence_Md(context, (Md) semanticObject); 
				return; 
			case MyDslPackage.METHOD_BACK:
				sequence_MethodBack(context, (MethodBack) semanticObject); 
				return; 
			case MyDslPackage.MODULE:
				sequence_Module(context, (org.xtext.example.mydsl.myDsl.Module) semanticObject); 
				return; 
			case MyDslPackage.NATIVE_CLASS:
				sequence_NativeClass(context, (NativeClass) semanticObject); 
				return; 
			case MyDslPackage.OPERATESON:
				sequence_Operateson(context, (Operateson) semanticObject); 
				return; 
			case MyDslPackage.OPERATION:
				sequence_Operation(context, (Operation) semanticObject); 
				return; 
			case MyDslPackage.PROPERTY:
				sequence_Property(context, (Property) semanticObject); 
				return; 
			case MyDslPackage.REACT_APP:
				sequence_ReactApp(context, (ReactApp) semanticObject); 
				return; 
			case MyDslPackage.REDUCER:
				sequence_Reducer(context, (Reducer) semanticObject); 
				return; 
			case MyDslPackage.RELATION_ARCH:
				sequence_RelationArch(context, (RelationArch) semanticObject); 
				return; 
			case MyDslPackage.RELATION_DOM:
				sequence_RelationDom(context, (RelationDom) semanticObject); 
				return; 
			case MyDslPackage.ROUTER_COMPONENT:
				sequence_RouterComponent(context, (RouterComponent) semanticObject); 
				return; 
			case MyDslPackage.SERVICE_FRONT:
				sequence_ServiceFront(context, (ServiceFront) semanticObject); 
				return; 
			case MyDslPackage.SPECIAL_ENTITY:
				sequence_SpecialEntity(context, (SpecialEntity) semanticObject); 
				return; 
			case MyDslPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case MyDslPackage.SUBLAYER_SEGMENT:
				sequence_SublayerSegment(context, (SublayerSegment) semanticObject); 
				return; 
			case MyDslPackage.SUBMODULE:
				sequence_Submodule(context, (Submodule) semanticObject); 
				return; 
			case MyDslPackage.SUBPROJECT:
				sequence_Subproject(context, (Subproject) semanticObject); 
				return; 
			case MyDslPackage.SYSTEM:
				sequence_System(context, (org.xtext.example.mydsl.myDsl.System) semanticObject); 
				return; 
			case MyDslPackage.TECHNOLOGY:
				sequence_Technology(context, (Technology) semanticObject); 
				return; 
			case MyDslPackage.TRANSACTION:
				sequence_Transaction(context, (Transaction) semanticObject); 
				return; 
			case MyDslPackage.TYPE:
				sequence_Type(context, (Type) semanticObject); 
				return; 
			case MyDslPackage.VISUALIZER:
				sequence_Visualizer(context, (Visualizer) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     AbstractClass returns AbstractClass
	 *     Eclass returns AbstractClass
	 *
	 * Constraint:
	 *     (name=ID attribute+=Attribute* methodClass+=MethodBack* annotation=[Annotation|ID]* abstractMethod+=AbstractMethod*)
	 */
	protected void sequence_AbstractClass(ISerializationContext context, AbstractClass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractMethod returns AbstractMethod
	 *
	 * Constraint:
	 *     (name=ID arg=[Eclass|ID]* type=[Eclass|ID]?)
	 */
	protected void sequence_AbstractMethod(ISerializationContext context, AbstractMethod semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns ActionCreator
	 *     ActionCreator returns ActionCreator
	 *
	 * Constraint:
	 *     (name=ID type=STRING)
	 */
	protected void sequence_ActionCreator(ISerializationContext context, ActionCreator semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ACTION_CREATOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ACTION_CREATOR__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ACTION_CREATOR__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ACTION_CREATOR__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getActionCreatorAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getActionCreatorAccess().getTypeSTRINGTerminalRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns ActionDispatcher
	 *     ActionDispatcher returns ActionDispatcher
	 *
	 * Constraint:
	 *     (name=ID type=[ActionCreator|ID]*)
	 */
	protected void sequence_ActionDispatcher(ISerializationContext context, ActionDispatcher semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Action
	 *     Action returns Action
	 *
	 * Constraint:
	 *     (name=ID actionCreator=[ActionCreator|ID]* actionDispatcher=[ActionDispatcher|ID]* dir=[Directory|ID])
	 */
	protected void sequence_Action(ISerializationContext context, org.xtext.example.mydsl.myDsl.Action semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Eclass returns Annotation
	 *     Annotation returns Annotation
	 *
	 * Constraint:
	 *     (name=ID propertie=STRING*)
	 */
	protected void sequence_Annotation(ISerializationContext context, Annotation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Architecture returns Architecture
	 *
	 * Constraint:
	 *     (componentes+=Component+ relationArch+=RelationArch+)
	 */
	protected void sequence_Architecture(ISerializationContext context, Architecture semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (name=ID type=[Eclass|ID])
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ATTRIBUTE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ATTRIBUTE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ATTRIBUTE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ATTRIBUTE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAttributeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAttributeAccess().getTypeEclassIDTerminalRuleCall_3_0_1(), semanticObject.eGet(MyDslPackage.Literals.ATTRIBUTE__TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns AxiosRequest
	 *     AxiosRequest returns AxiosRequest
	 *
	 * Constraint:
	 *     (name=ID (axiosRestMethod='getMethod' | axiosRestMethod='postMethod') url=STRING data=JsMethodArgs?)
	 */
	protected void sequence_AxiosRequest(ISerializationContext context, AxiosRequest semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Component returns Component
	 *
	 * Constraint:
	 *     (name=ComponentName layer+=Layer+)
	 */
	protected void sequence_Component(ISerializationContext context, Component semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Container
	 *     Container returns Container
	 *
	 * Constraint:
	 *     (name=ID type=[Directory|ID] type=[ActionDispatcher|ID]? type=[Reducer|ID]* type=[JsModule|ID])
	 */
	protected void sequence_Container(ISerializationContext context, Container semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Css
	 *     File returns Css
	 *     Css returns Css
	 *
	 * Constraint:
	 *     (name=ID type=STRING)
	 */
	protected void sequence_Css(ISerializationContext context, Css semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getCssAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getCssAccess().getTypeSTRINGTerminalRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Descriptor returns Descriptor
	 *
	 * Constraint:
	 *     (name=ID path=STRING)
	 */
	protected void sequence_Descriptor(ISerializationContext context, Descriptor semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.DESCRIPTOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.DESCRIPTOR__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.DESCRIPTOR__PATH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.DESCRIPTOR__PATH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDescriptorAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getDescriptorAccess().getPathSTRINGTerminalRuleCall_4_0(), semanticObject.getPath());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Directory
	 *     Directory returns Directory
	 *
	 * Constraint:
	 *     (name=ID file=[File|ID]* subdirectory=[Directory|ID]* purpose=STRING)
	 */
	protected void sequence_Directory(ISerializationContext context, Directory semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Domain returns Domain
	 *
	 * Constraint:
	 *     (types+=Type* modules+=Module+ relations+=RelationDom+)
	 */
	protected void sequence_Domain(ISerializationContext context, Domain semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Einterface returns Einterface
	 *
	 * Constraint:
	 *     (name=ID attribute+=Attribute* abstractMethod+=AbstractMethod*)
	 */
	protected void sequence_Einterface(ISerializationContext context, Einterface semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     EntityName returns EntityName
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_EntityName(ISerializationContext context, EntityName semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.ENTITY_NAME__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.ENTITY_NAME__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getEntityNameAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Epackage returns Epackage
	 *
	 * Constraint:
	 *     (name=ID eclass+=Eclass*)
	 */
	protected void sequence_Epackage(ISerializationContext context, Epackage semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Functionality
	 *     Functionality returns Functionality
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         route=[RouterComponent|ID]* 
	 *         wrap=[Container|ID]* 
	 *         render=[Visualizer|ID]+ 
	 *         state=[State|ID]* 
	 *         service=[ServiceFront|ID]* 
	 *         type=[Directory|ID]
	 *     )
	 */
	protected void sequence_Functionality(ISerializationContext context, Functionality semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GeneralEntity returns GeneralEntity
	 *
	 * Constraint:
	 *     (name=EntityName properties+=Property+)
	 */
	protected void sequence_GeneralEntity(ISerializationContext context, GeneralEntity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     GenericClass returns GenericClass
	 *     Eclass returns GenericClass
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         attribute+=Attribute* 
	 *         methodClass+=MethodBack* 
	 *         annotation=[Annotation|ID]* 
	 *         abs=[AbstractClass|ID]? 
	 *         imp=[Einterface|ID]*
	 *     )
	 */
	protected void sequence_GenericClass(ISerializationContext context, GenericClass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     JavaApp returns JavaApp
	 *
	 * Constraint:
	 *     jeeproject+=JeeProject
	 */
	protected void sequence_JavaApp(ISerializationContext context, JavaApp semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     JeeProject returns JeeProject
	 *
	 * Constraint:
	 *     (name=ID subproject+=Subproject+)
	 */
	protected void sequence_JeeProject(ISerializationContext context, JeeProject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     JsMethodArgs returns JsMethodArgs
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_JsMethodArgs(ISerializationContext context, JsMethodArgs semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.JS_METHOD_ARGS__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.JS_METHOD_ARGS__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getJsMethodArgsAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     JsMethod returns JsMethod
	 *
	 * Constraint:
	 *     (name=ID type=JsMethodType arguments+=JsMethodArgs*)
	 */
	protected void sequence_JsMethod(ISerializationContext context, JsMethod semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns JsModule
	 *     JsModule returns JsModule
	 *
	 * Constraint:
	 *     (name=ID type=[Directory|ID])
	 */
	protected void sequence_JsModule(ISerializationContext context, JsModule semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.JS_MODULE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.JS_MODULE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.JS_MODULE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.JS_MODULE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getJsModuleAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getJsModuleAccess().getTypeDirectoryIDTerminalRuleCall_4_0_1(), semanticObject.eGet(MyDslPackage.Literals.JS_MODULE__TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Js
	 *     File returns Js
	 *     Js returns Js
	 *
	 * Constraint:
	 *     (name=ID type=STRING)
	 */
	protected void sequence_Js(ISerializationContext context, Js semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getJsAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getJsAccess().getTypeSTRINGTerminalRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Json
	 *     File returns Json
	 *     Json returns Json
	 *
	 * Constraint:
	 *     (name=ID type=STRING)
	 */
	protected void sequence_Json(ISerializationContext context, Json semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getJsonAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getJsonAccess().getTypeSTRINGTerminalRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     LayerSegmentRelation returns LayerSegmentRelation
	 *
	 * Constraint:
	 *     layerSegment=LayerSegmentName
	 */
	protected void sequence_LayerSegmentRelation(ISerializationContext context, LayerSegmentRelation semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.LAYER_SEGMENT_RELATION__LAYER_SEGMENT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.LAYER_SEGMENT_RELATION__LAYER_SEGMENT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLayerSegmentRelationAccess().getLayerSegmentLayerSegmentNameParserRuleCall_1_0(), semanticObject.getLayerSegment());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     LayerSegment returns LayerSegment
	 *
	 * Constraint:
	 *     (name=LayerSegmentName relations+=LayerSegmentRelation* sublayerSegments+=SublayerSegment*)
	 */
	protected void sequence_LayerSegment(ISerializationContext context, LayerSegment semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Layer returns Layer
	 *
	 * Constraint:
	 *     (name=LayerName layerSegments+=LayerSegment*)
	 */
	protected void sequence_Layer(ISerializationContext context, Layer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Library returns Library
	 *
	 * Constraint:
	 *     (name=ID isNative=Boolean annotation+=Annotation*)
	 */
	protected void sequence_Library(ISerializationContext context, Library semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Md
	 *     File returns Md
	 *     Md returns Md
	 *
	 * Constraint:
	 *     (name=ID type=STRING)
	 */
	protected void sequence_Md(ISerializationContext context, Md semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FILE__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FILE__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMdAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getMdAccess().getTypeSTRINGTerminalRuleCall_4_0(), semanticObject.getType());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     MethodBack returns MethodBack
	 *
	 * Constraint:
	 *     (name=ID arg=[Eclass|ID]* type=[Eclass|ID]?)
	 */
	protected void sequence_MethodBack(ISerializationContext context, MethodBack semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Module returns Module
	 *
	 * Constraint:
	 *     (name=ID submodules+=Submodule+)
	 */
	protected void sequence_Module(ISerializationContext context, org.xtext.example.mydsl.myDsl.Module semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     NativeClass returns NativeClass
	 *     Eclass returns NativeClass
	 *
	 * Constraint:
	 *     (name=ID attribute+=Attribute* methodClass+=MethodBack*)
	 */
	protected void sequence_NativeClass(ISerializationContext context, NativeClass semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Operateson returns Operateson
	 *
	 * Constraint:
	 *     operateson+=EntityName
	 */
	protected void sequence_Operateson(ISerializationContext context, Operateson semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Operation returns Operation
	 *
	 * Constraint:
	 *     (type=SubOperation target+=EntityName)
	 */
	protected void sequence_Operation(ISerializationContext context, Operation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Property returns Property
	 *
	 * Constraint:
	 *     (name=ID type=[Type|ID])
	 */
	protected void sequence_Property(ISerializationContext context, Property semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.PROPERTY__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.PROPERTY__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.PROPERTY__TYPE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.PROPERTY__TYPE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPropertyAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPropertyAccess().getTypeTypeIDTerminalRuleCall_2_0_1(), semanticObject.eGet(MyDslPackage.Literals.PROPERTY__TYPE, false));
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns ReactApp
	 *     ReactApp returns ReactApp
	 *
	 * Constraint:
	 *     (elements+=AbstractFrontElement+ func=[Functionality|ID]+ dir=[Directory|ID]+ mod=[JsModule|ID]+)
	 */
	protected void sequence_ReactApp(ISerializationContext context, ReactApp semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Reducer
	 *     Reducer returns Reducer
	 *
	 * Constraint:
	 *     (name=ID type=[ActionCreator|ID]+ type=[Directory|ID])
	 */
	protected void sequence_Reducer(ISerializationContext context, Reducer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     RelationArch returns RelationArch
	 *
	 * Constraint:
	 *     (name=ID source=LayerName target=LayerName)
	 */
	protected void sequence_RelationArch(ISerializationContext context, RelationArch semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.RELATION_ARCH__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.RELATION_ARCH__NAME));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.RELATION_ARCH__SOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.RELATION_ARCH__SOURCE));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.RELATION_ARCH__TARGET) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.RELATION_ARCH__TARGET));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getRelationArchAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getRelationArchAccess().getSourceLayerNameParserRuleCall_4_0(), semanticObject.getSource());
		feeder.accept(grammarAccess.getRelationArchAccess().getTargetLayerNameParserRuleCall_7_0(), semanticObject.getTarget());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     RelationDom returns RelationDom
	 *
	 * Constraint:
	 *     (source+=EntityName target+=EntityName)
	 */
	protected void sequence_RelationDom(ISerializationContext context, RelationDom semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns RouterComponent
	 *     RouterComponent returns RouterComponent
	 *     UIComponent returns RouterComponent
	 *
	 * Constraint:
	 *     (name=ID type=[Directory|ID] type=[JsModule|ID] route=[UIComponent|ID])
	 */
	protected void sequence_RouterComponent(ISerializationContext context, RouterComponent semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns ServiceFront
	 *     ServiceFront returns ServiceFront
	 *
	 * Constraint:
	 *     (name=ID type=[JsModule|ID] method=STRING+ requests+=AxiosRequest+)
	 */
	protected void sequence_ServiceFront(ISerializationContext context, ServiceFront semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SpecialEntity returns SpecialEntity
	 *
	 * Constraint:
	 *     (name=EntityName properties+=Property+ transactions+=Transaction+)
	 */
	protected void sequence_SpecialEntity(ISerializationContext context, SpecialEntity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns State
	 *     State returns State
	 *
	 * Constraint:
	 *     (name=ID action=[Action|ID]* reducer=[Reducer|ID]*)
	 */
	protected void sequence_State(ISerializationContext context, State semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     SublayerSegment returns SublayerSegment
	 *
	 * Constraint:
	 *     name=SublayerSegmentName
	 */
	protected void sequence_SublayerSegment(ISerializationContext context, SublayerSegment semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.SUBLAYER_SEGMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.SUBLAYER_SEGMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSublayerSegmentAccess().getNameSublayerSegmentNameParserRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Submodule returns Submodule
	 *
	 * Constraint:
	 *     (name=ID operations+=Operation+ (entities+=GeneralEntity | entities+=SpecialEntity)+)
	 */
	protected void sequence_Submodule(ISerializationContext context, Submodule semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Subproject returns Subproject
	 *
	 * Constraint:
	 *     (name=ID epackage+=Epackage+ library+=Library+ descriptor+=Descriptor+)
	 */
	protected void sequence_Subproject(ISerializationContext context, Subproject semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     System returns System
	 *
	 * Constraint:
	 *     (dom=Domain arch=Architecture tech=Technology)
	 */
	protected void sequence_System(ISerializationContext context, org.xtext.example.mydsl.myDsl.System semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.SYSTEM__DOM) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.SYSTEM__DOM));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.SYSTEM__ARCH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.SYSTEM__ARCH));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.SYSTEM__TECH) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.SYSTEM__TECH));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getSystemAccess().getDomDomainParserRuleCall_2_0(), semanticObject.getDom());
		feeder.accept(grammarAccess.getSystemAccess().getArchArchitectureParserRuleCall_3_0(), semanticObject.getArch());
		feeder.accept(grammarAccess.getSystemAccess().getTechTechnologyParserRuleCall_4_0(), semanticObject.getTech());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Technology returns Technology
	 *
	 * Constraint:
	 *     (java=JavaApp react=ReactApp)
	 */
	protected void sequence_Technology(ISerializationContext context, Technology semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.TECHNOLOGY__JAVA) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.TECHNOLOGY__JAVA));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.TECHNOLOGY__REACT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.TECHNOLOGY__REACT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTechnologyAccess().getJavaJavaAppParserRuleCall_2_0(), semanticObject.getJava());
		feeder.accept(grammarAccess.getTechnologyAccess().getReactReactAppParserRuleCall_3_0(), semanticObject.getReact());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Transaction returns Transaction
	 *
	 * Constraint:
	 *     (type=SubTransaction operateson+=Operateson+)
	 */
	protected void sequence_Transaction(ISerializationContext context, Transaction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Type returns Type
	 *     AbstractFrontElement returns Type
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Type(ISerializationContext context, Type semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.TYPE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.TYPE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getTypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     AbstractFrontElement returns Visualizer
	 *     UIComponent returns Visualizer
	 *     Visualizer returns Visualizer
	 *
	 * Constraint:
	 *     (name=ID type=[Directory|ID] type=[JsModule|ID]+ methods+=JsMethod+)
	 */
	protected void sequence_Visualizer(ISerializationContext context, Visualizer semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
