/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Abstract Class</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AbstractClass#getAttribute <em>Attribute</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AbstractClass#getMethodClass <em>Method Class</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AbstractClass#getAnnotation <em>Annotation</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.AbstractClass#getAbstractMethod <em>Abstract Method</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAbstractClass()
 * @model
 * @generated
 */
public interface AbstractClass extends Eclass
{
  /**
   * Returns the value of the '<em><b>Attribute</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Attribute}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attribute</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAbstractClass_Attribute()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttribute();

  /**
   * Returns the value of the '<em><b>Method Class</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.MethodBack}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Method Class</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAbstractClass_MethodClass()
   * @model containment="true"
   * @generated
   */
  EList<MethodBack> getMethodClass();

  /**
   * Returns the value of the '<em><b>Annotation</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Annotation</em>' reference.
   * @see #setAnnotation(Annotation)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAbstractClass_Annotation()
   * @model
   * @generated
   */
  Annotation getAnnotation();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.AbstractClass#getAnnotation <em>Annotation</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Annotation</em>' reference.
   * @see #getAnnotation()
   * @generated
   */
  void setAnnotation(Annotation value);

  /**
   * Returns the value of the '<em><b>Abstract Method</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.AbstractMethod}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Abstract Method</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAbstractClass_AbstractMethod()
   * @model containment="true"
   * @generated
   */
  EList<AbstractMethod> getAbstractMethod();

} // AbstractClass
