/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Annotation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Annotation#getPropertie <em>Propertie</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAnnotation()
 * @model
 * @generated
 */
public interface Annotation extends Eclass
{
  /**
   * Returns the value of the '<em><b>Propertie</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Propertie</em>' attribute.
   * @see #setPropertie(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getAnnotation_Propertie()
   * @model
   * @generated
   */
  String getPropertie();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Annotation#getPropertie <em>Propertie</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Propertie</em>' attribute.
   * @see #getPropertie()
   * @generated
   */
  void setPropertie(String value);

} // Annotation
