/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Md</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getMd()
 * @model
 * @generated
 */
public interface Md extends File
{
} // Md
