/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operateson</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Operateson#getOperateson <em>Operateson</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperateson()
 * @model
 * @generated
 */
public interface Operateson extends EObject
{
  /**
   * Returns the value of the '<em><b>Operateson</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.EntityName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operateson</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getOperateson_Operateson()
   * @model containment="true"
   * @generated
   */
  EList<EntityName> getOperateson();

} // Operateson
