/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Special Entity</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SpecialEntity#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SpecialEntity#getProperties <em>Properties</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.SpecialEntity#getTransactions <em>Transactions</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSpecialEntity()
 * @model
 * @generated
 */
public interface SpecialEntity extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(EntityName)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSpecialEntity_Name()
   * @model containment="true"
   * @generated
   */
  EntityName getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.SpecialEntity#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(EntityName value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Property}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSpecialEntity_Properties()
   * @model containment="true"
   * @generated
   */
  EList<Property> getProperties();

  /**
   * Returns the value of the '<em><b>Transactions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.Transaction}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Transactions</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getSpecialEntity_Transactions()
   * @model containment="true"
   * @generated
   */
  EList<Transaction> getTransactions();

} // SpecialEntity
