/**
 * generated by Xtext 2.18.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Technology</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Technology#getJava <em>Java</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Technology#getReact <em>React</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTechnology()
 * @model
 * @generated
 */
public interface Technology extends EObject
{
  /**
   * Returns the value of the '<em><b>Java</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Java</em>' containment reference.
   * @see #setJava(JavaApp)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTechnology_Java()
   * @model containment="true"
   * @generated
   */
  JavaApp getJava();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Technology#getJava <em>Java</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Java</em>' containment reference.
   * @see #getJava()
   * @generated
   */
  void setJava(JavaApp value);

  /**
   * Returns the value of the '<em><b>React</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>React</em>' containment reference.
   * @see #setReact(ReactApp)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getTechnology_React()
   * @model containment="true"
   * @generated
   */
  ReactApp getReact();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Technology#getReact <em>React</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>React</em>' containment reference.
   * @see #getReact()
   * @generated
   */
  void setReact(ReactApp value);

} // Technology
